### ISSUE TITLE
Prometheus Settings?

### ISSUE THREAD

**Issue by lastb0isct** [yvasiyarov/zfs-dashboard#1]
I'm completely new to prometheus and am curious what settings are needed to be done on prometheus side of things to get this working?  I have it installed but not sure what I need to configure to get my zfs data in it...

**Comment by yvasiyarov** [comment]
@lastb0isct please have a look at the installation steps in ReadMe file. 
To get your data in you need to:
- configure Telegraf and its ZFS monitoring plugin.
- configure target in Prometheus (so it will start collecting metrics from Telegraf)

**Comment by lastb0isct** [comment]
I configured the telegraf zfs plugin, but the ReadMe file mentions no configuration of prometheus:

```
Enable ZFS Input Plugin
Enable Pool Metrics collection: set poolMetrics = true in telegraf.conf
Import this dashboard into Grafana https://grafana.com/docs/grafana/latest/reference/export_import/
Profit!
```
This is why i'm confused...do I have to configure telegraf with a prometheus output or input plugin? Do I configure prometheus with a scrape config?

Thanks for the help!

**Comment by yvasiyarov** [comment]
> do I have to configure telegraf with a prometheus output or input plugin
yes, you need to configure telegraf with prometheus output plugin

>Do I configure prometheus with a scrape config?
yes, you need to configure prometheus to scrape metrics from your telegraf installation.

Sorry that I'm forget to mention this points. I assume that it should be part of "Enable ZFS Input Plugin"

**Comment by lastb0isct** [comment]
Thank you! -- Sorry, i'm just a noob at prometheus and telegraf so this really helped me out! I'll get to implementing this soon!

**Comment by lastb0isct** [comment]
Thank you for all your help on this! I was able to get Prometheus working and have all of my data available in Grafana.  Only issue is that ZoL doesn't have the same stats and I can't get a lot of the stats, or don't know which ones they would correspond to on ZoL.  So looks like i'll have to figure out how to get those stats available...

**Comment by yvasiyarov** [comment]
@lastb0isct unfortunately I failed to push through my PR to telegraph. Maintainers do not want to merge it.
So only option I can offer - is to checkout my PR and build telegraph from the source code. In that case all metrics will be available for you.
